### PR TITLE
Add support for Julia

### PR DESCRIPTION
**Pull request by abhishalya**
This adds support for [Julia](https://julialang.org/). [[Github](https://github.com/julialang)]

Julia has many many packages (more than 3000)! And almost every other package has documentation written in [Documenter.jl](https://github.com/JuliaDocs/Documenter.jl). Julia also has a static site generator [Franklin.jl](https://github.com/tlienart/Franklin.jl) which is quite unique and is improving a lot.

In fact the [main Julia site](https://julialang.org/) is generated using Franklin.jl.

With this, I think it would be very helpful for us to have Julia support on Netlify.

### CODE REVIEW

**Comment by logankilpatrick** [comment]
Hey @mraerino, I would be happy to beta test this for the JuliaLang.org site if possible.

**Comment by ViralBShah** [comment]
Would be really nice to have this, as a number of Julia's [Franklin.jl](https://franklinjl.org) based sites would like to use netlify.

**Comment by mraerino** [comment]
we are currently considering how we can best let people beta test these changes. stay tuned.

**Comment by abhishalya** [comment]
Wow, this is really great. Lots of thumbs up in just few hours. I'll test and fine tune this PR.

**Comment by DilumAluthge** [comment]
Bump. Any update on this?

**Comment by kitop** [comment]
Closing this PR as the it's against xenial branch and the Xenial image is going to be deprecated: https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

**Pull request closed without merging**
