### PR TITLE
Prebuild steps

### PR DESCRIPTION
**Pull request by dz0ny**
I believe this is the way to implement the pre-build changes needed by many issues with the current build process. It allows a bit more flexibility for advanced users and does not break things for existing users.

Here are some examples:

## Skipping unnecessary language installs (https://github.com/netlify/build-image/issues/141)

One can create `.netlify/remove_languages.sh` with contents:
```bash
rm Pipfile
rm Pipfile.lock
rm requirements.txt
rm runtime.txt
```

## Specify Composer file (https://github.com/netlify/build-image/issues/237)

One can create `.netlify/patch_composer.sh` with contents:
```bash
mv -f composer-netlify.json composer.json
```

## Deploying multiple sites from the same repo (https://github.com/netlify/build-image/issues/196)

Add enviroment vairable $NETLIFY_SITE to project
Create a `.netlify/netfily-site.sh` with contents:
```bash
mv -f .netlify/$NETLIFY_SITE netlify.yaml
```

### CODE REVIEW

**Comment by jafri** [comment]
Can you have a look at this @bcomnes @bkuhlmann

**Comment by bkuhlmann** [comment]
From my perspective, this doesn't hurt anything with the [Git Cop](https://github.com/bkuhlmann/git-cop) linter as it only cares about the `NETLIFY` [environment variable](https://github.com/bkuhlmann/git-cop#netlify-ci). As long as that variable remains set, Git Cop can auto-detect the build environment properly.

:bulb: Might be good to document both the `NETLIFY` and `NETLIFY_SITE` variables on the Netlify [Environment Variables](https://www.netlify.com/docs/continuous-deployment/#environment-variables) page, though (not the responsibility of this issue, I guess).

**Comment by dz0ny** [comment]
ping

**Comment by agarzola** [comment]
I’m interested in the functionality proposed here. Any chance this PR can get reviewed and merged and these pre-build hooks rolled out?

**Comment by dz0ny** [comment]
They have their own way to do this, see https://docs.netlify.com/configure-builds/build-plugins/create-plugins/

**Pull request closed without merging**
