### PR TITLE
Add ruby 2.5.1 by rvm

### PR DESCRIPTION
**Pull request by unasuke**
related issue →  #123

### CODE REVIEW

**Comment by brycekahle** [comment]
@unasuke Have you attempted installation of ruby 2.5.1 using the `RUBY_VERSION` environment variable? As far as we know, this still does not work using `rvm`.

**Comment by unasuke** [comment]
@brycekahle 

> As far as we know, this still does not work using rvm.

But, for now, install Ruby 2.5.1 by rvm is succeed. I created the pull request because I confirmed succeed build the image.
Could you try to build the docker image?

**Comment by brycekahle** [comment]
@unasuke I will attempt to build the docker image. Have you tried a Netlify build (not a docker build of the image in this repo) using the `RUBY_VERSION=2.5.1` environment variable?

**Comment by migueldemoura** [comment]
@brycekahle I atempted to do that and failed: https://github.com/migueldemoura/migueldemoura.com/issues/7

I used both `RUBY_VERSION=2.5.1` and pining the version in the `Gemfile`.

I'll attach some logs in a sec.

**Comment by unasuke** [comment]
hmm...?

```shell
$ docker run -it unasuke/netlify-build-image bash
buildbot@836eec294c76:/$ RUBY_VERSION=2.5.1
buildbot@836eec294c76:/$ source $HOME/.rvm/scripts/rvm
buildbot@836eec294c76:/$ rvm use 2.5.1
Using /opt/buildhome/.rvm/gems/ruby-2.5.1
buildbot@836eec294c76:/$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
buildbot@836eec294c76:/$
```

**Comment by brycekahle** [comment]
@unasuke The problem appears when you try to actually use bundler with that version of Ruby.

**Comment by migueldemoura** [comment]
@brycekahle, that's the issue, yes.

**Comment by unasuke** [comment]
@brycekahle 

> The problem appears when you try to actually use bundler with that version of Ruby.

I tried to install rails by bundler, it was succeeded.

```shell
% docker run  -it unasuke/netlify-build-image bash
buildbot@b0b1a82b0f3b:~$ RUBY_VERSION=2.5.1
buildbot@b0b1a82b0f3b:~$ source $HOME/.rvm/scripts/rvm; rvm use 2.5.1
Using /opt/buildhome/.rvm/gems/ruby-2.5.1
buildbot@b0b1a82b0f3b:~$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
buildbot@b0b1a82b0f3b:/tmp/test$ gem install --no-ri bundler
Successfully installed bundler-1.16.1
1 gem installed
buildbot@b0b1a82b0f3b:~$ cat Gemfile
source 'https://rubygems.org'
gem 'rails'
buildbot@b0b1a82b0f3b:~$ bundle install
Fetching gem metadata from https://rubygems.org/................
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 12.3.1
Using concurrent-ruby 1.0.5
###### snip
Using sprockets-rails 3.2.1
Using rails 5.2.0
Bundle complete! 1 Gemfile dependency, 41 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
buildbot@b0b1a82b0f3b:~$ rails --version
Rails 5.2.0
buildbot@b0b1a82b0f3b:~$
```

**Comment by unasuke** [comment]
@migueldemoura 

It seems succeeded.

```shell
buildbot@b0b1a82b0f3b:~$ git clone https://github.com/migueldemoura/migueldemoura.com.git
Cloning into 'migueldemoura.com'...
remote: Counting objects: 979, done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 979 (delta 40), reused 60 (delta 22), pack-reused 889
Receiving objects: 100% (979/979), 2.40 MiB | 1.52 MiB/s, done.
Resolving deltas: 100% (524/524), done.
buildbot@b0b1a82b0f3b:~$ cd migueldemoura.com/
buildbot@b0b1a82b0f3b:~/migueldemoura.com$ git rev-parse HEAD
339d16814fe96e75927387b758c85a4cc0d8d541
buildbot@b0b1a82b0f3b:~/migueldemoura.com$ bundle install --quiet
buildbot@b0b1a82b0f3b:~/migueldemoura.com$ source $HOME/.nvm/nvm.sh
buildbot@b0b1a82b0f3b:~/migueldemoura.com$ npm -v
5.6.0


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.6.0 → 6.0.0    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯

buildbot@b0b1a82b0f3b:~/migueldemoura.com$ npm i
npm notice created a lockfile as package-lock.json. You should commit this file.
added 413 packages in 8.046s
buildbot@b0b1a82b0f3b:~/migueldemoura.com$ bundle exec jekyll build
Configuration file: /opt/buildhome/migueldemoura.com/_config.yml
            Source: /opt/buildhome/migueldemoura.com
       Destination: /opt/buildhome/migueldemoura.com/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 5.76 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
buildbot@b0b1a82b0f3b:~/migueldemoura.com$ ls -al _site/
total 52
drwxr-xr-x 1 buildbot nogroup   180 May  3 14:49 .
drwxr-xr-x 1 buildbot nogroup   560 May  3 14:49 ..
-rw-r--r-- 1 buildbot nogroup  2031 May  3 14:49 404.html
-rw-r--r-- 1 buildbot nogroup  5859 May  3 14:49 about.html
drwxr-xr-x 1 buildbot nogroup  9676 May  3 14:49 assets
-rw-r--r-- 1 buildbot nogroup 15086 May  3 14:40 favicon.ico
-rw-r--r-- 1 buildbot nogroup  1762 May  3 14:49 feed.xml
-rw-r--r-- 1 buildbot nogroup   529 May  3 14:40 _headers
-rw-r--r-- 1 buildbot nogroup  7124 May  3 14:49 index.html
drwxr-xr-x 1 buildbot nogroup   168 May  3 14:49 posts
-rw-r--r-- 1 buildbot nogroup    24 May  3 14:40 robots.txt
-rw-r--r-- 1 buildbot nogroup  1382 May  3 14:49 sitemap.xml
drwxr-xr-x 1 buildbot nogroup    94 May  3 14:49 tag
buildbot@b0b1a82b0f3b:~/migueldemoura.com$
```

**Comment by migueldemoura** [comment]
Did you set the ruby version? I downgraded ruby in that repo, version isn't specified anywhere.

**Comment by unasuke** [comment]
@migueldemoura 

Yes. I use ruby 2.5.1

```shell
buildbot@b0b1a82b0f3b:~/migueldemoura.com$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
buildbot@b0b1a82b0f3b:~/migueldemoura.com$ bundle exec jekyll build
Configuration file: /opt/buildhome/migueldemoura.com/_config.yml
            Source: /opt/buildhome/migueldemoura.com
       Destination: /opt/buildhome/migueldemoura.com/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 1.083 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
buildbot@b0b1a82b0f3b:~/migueldemoura.com$
```

**Comment by migueldemoura** [comment]
I'm going to run it as well to confirm. Build fails on Netlify, but maybe it works with your patch, idk.

**Comment by unasuke** [comment]
@migueldemoura Yes, You set env `RUBY_VERSION` to `2.5.1` then you can use ruby 2.5.1 maybe.

screenshot from 2018-05-04 00-16-11

**Comment by migueldemoura** [comment]
Setting the env variable makes the build fail with the output I've attached before. You can try it by forking my repo, attaching it to netlify and triggering a deploy.

**Comment by unasuke** [comment]
@migueldemoura Could you use ruby 2.4? Ruby 2.5.1 is not available on netlify now. (so I created the pull request  to use ruby 2.5.1 on netlify...)

**Comment by migueldemoura** [comment]
Yes, that's what I meant with
> The commands to use a custom ruby version are the same as your patch?

Having that version already installed allows the build to succeed, but installing it on the fly makes it fail. I think this can be merged.

Should probably also upgrade the ruby versions to the latest minor releases, especially since they have security patches. @brycekahle

**Comment by brycekahle** [comment]
That is very curious. There really should be no difference between installing Ruby during the image build and during a Netlify build. Both are using `rvm`.

I'm going to do a bit more investigation before merging this. The point of the `RUBY_VERSION` environment variable is to allow any ruby version to be installed on-demand. I don't want to leave a minefield if someone wants to use `2.5.0` when `2.5.1` is the version pre-installed.

**Comment by unasuke** [comment]
I created #170 . So close this. Thanks!

**Comment by migueldemoura** [comment]
@brycekahle, just tested with another custom version of ruby, 2.4.4, and I get the same error:

```
6:31:33 PM: /opt/buildhome/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/dep_proxy (LoadError)
6:31:33 PM: 	from /opt/buildhome/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
6:31:33 PM: 	from /opt/buildhome/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/definition.rb:888:in `block (2 levels) in expand_dependencies'
6:31:33 PM: 	from /opt/buildhome/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/definition.rb:887:in `each'
6:31:33 PM: 	from /opt/buildhome/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/definition.rb:887:in `block in expand_dependencies'
6:31:33 PM: 	from /opt/buildhome/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/definition.rb:874:in `each'
6:31:33 PM: 	from /opt/buildhome/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/definition.rb:874:in `expand_dependencies'
6:31:33 PM: 	from /opt/buildhome/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/definition.rb:806:in `converge_locked_specs'
6:31:33 PM: 	from /opt/buildhome/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/definition.rb:247:in `resolve'
6:31:33 PM: 	from /opt/buildhome/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
6:31:33 PM: 	from /opt/buildhome/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
6:31:33 PM: 	from /opt/buildhome/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
6:31:33 PM: 	from /opt/buildhome/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
6:31:33 PM: 	from /opt/buildhome/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
6:31:33 PM: 	from /opt/buildhome/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
6:31:33 PM: 	from /opt/buildhome/.rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/setup.rb:20:in `<top (required)>'
6:31:33 PM: 	from /opt/buildhome/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
6:31:33 PM: 	from /opt/buildhome/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
6:31:33 PM: 	from /opt/build/cache/binstubs/jekyll:27:in `<main>'
```

**Pull request closed without merging**
