### PR TITLE
Update Binrc to support Hugo Expanded.

### PR DESCRIPTION
**Pull request by calavera**
This will allow us to install the new expanded version of Hugo.

:warning: :warning: **DO NOT MERGE** :warning: :warning: 

This is blocked by netlify/build-image#183

Signed-off-by: David Calavera <david.calavera@gmail.com>

### CODE REVIEW

**Comment by brycekahle** [comment]
I don't think we can switch to Ubuntu 16 so quickly. Anyone who is using a pre-built binary will be broken by this change.

**Comment by igk1972** [comment]
Fast workaround https://github.com/netlify/build-image/issues/183#issuecomment-419199649

**Comment by Keats** [comment]
Any chance to get https://github.com/netlify/binrc/pull/19 merged and bump the binrc release once more in that PR?

**Comment by bcomnes** [comment]
This is (effectively) merged into the 3.x.x image.  Thank you @calavera !

**Pull request closed without merging**
