### PR TITLE
Allow for custom npmrc file

### LINKED ISSUE #423: Add authentication string to .npmrc for Github packages
Hey there 👋

There's currently some issues Netlify users are experiencing connecting their projects with the Github package repository and private packages.  See [this](https://community.netlify.com/t/support-guide-using-private-npm-modules-on-netlify/795/30).

The problem is that you need a `.npmrc` file pointing to the github registry which contains the auth token. For example: registry=https://npm.pkg.github.com/:_authToken=${TOKEN}.  There's no way to add this file during the build process before the Netlify system runs `npm install`, and including the file on your local machine forces you to define `TOKEN` in your environment to be able to run `npm install`.  This makes onboarding and cross-platform work a challenge, especially when npm already has a clearly documented command for authenticating: `npm login`.

Now, after poking around in some of the files, I found [this](https://github.com/netlify/build-image/blob/xenial/run-build-functions.sh#L235) line.  When `NPM_TOKEN` is defined, and no `.npmrc` file exists, the build script automatically creates the `.npmrc` file with the registry authentication line.

Is it possible to have this functionality extended to Github?  Given the rising popularity of Github packages, and the lack of an easy workaround (one that doesnt require extra setup for projects), I think this makes sense to add.

The environment variable could be `GITHUB_PACKAGES_TOKEN`. 

I'd be more than happy to work on this change, I'm just not sure if this is something that you'd consider adding.

### PR DESCRIPTION
**Pull request by itsjoekent**
🎉 Thanks for submitting a pull request! 🎉

#### Summary

Fixes #423

Along with many open-ended Netlify support request threads/comments, eg:
https://answers.netlify.com/t/support-guide-using-private-npm-modules-on-netlify/795/57

[This answer](https://answers.netlify.com/t/support-guide-using-private-npm-modules-on-netlify/795/57) on the Netlify forums best explains why the current `NPM_TOKEN` and `.npmrc` committed to the repo is not a great solution.

> Directly adding the .npmrc file causes local npm installs to fail due to missing the variable ie: //npm.pkg.github.com/:_authToken=${NPM_TOKEN}. Given that developers normally login to npm using the npm login command locally, there should be absolutely no reason for them to also need to set NPM_TOKEN on their machine just so that npm install can work on their machine.

Many of the comments I found across the web & the above forum posts are looking for a custom "pre install" step, but for the most common use case requested (add a custom npmrc file before install), that seems like an over-complication.

This PR adds two new options,

1. A `GITHUB_PACKAGES_TOKEN` environment variable that creates an npmrc file for the GitHub packages registry.
2. A `NPM_RC` environment variable that lets you create a custom npmrc file, especially useful when you want to define custom scoped registries.

---

For us to review and ship your PR efficiently, please perform the following steps:

- [x] Open a [bug/issue](https://github.com/netlify/build-image/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [x] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and passes our tests.
- [x] Update or add tests (if any source code was changed or added) 🧪
- [ ] Update the [included software doc](../included_software.md) (if you updated included software) 📄
- [ ] Update or add documentation (if features were changed or added) 📝
- [ ] Make sure the status checks below are successful ✅

**A picture of a cute animal (not mandatory, but encouraged)**

image

### CODE REVIEW

**Comment by itsjoekent** [comment]
Closing this in favor of using: https://github.com/netlify/build-image/pull/854

**Comment by robnewton** [comment]
This appears to be what I am looking for (resolving private packages from github registries) but I don't understand how to linked PR covers it.

**Comment by itsjoekent** [comment]
@robnewton You can run a [pre-script](https://docs.npmjs.com/cli/v9/using-npm/scripts#pre--post-scripts) before the npm install happens, and that script outputs your custom `.npmrc` file. You could place the contents of the npmrc in an environment variable, `"NPMRC=@yourorg:registry=https://registry.example.com\n//registry.example.com/:authToken=123abc`, and your `postinstall` would be `echo $NPMRC > .npmrc`

**Comment by itsjoekent** [comment]
@robnewton FWIW, a simpler workaround we used is to create a `netlify` folder in your repo, place the `.npmrc` in that (to avoid using the `npm` command),

```
always-auth=true
//registry.npmjs.org/
//npm.pkg.github.com/:_authToken=${GITHUB_PACKAGES_TOKEN}
@your_org_name:registry=https://npm.pkg.github.com/
```

and then in your `netlify.toml` add the following,

```toml
[build.environment]
  NPM_CONFIG_USERCONFIG = "./netlify/.npmrc"
```

**Comment by robnewton** [comment]
@itsjoekent 

> and then in your `netlify.toml` add the following,
> 
> ```toml
> [build.environment]
>   NPM_CONFIG_USERCONFIG = "./netlify/.npmrc"
> ```

Yeah, I just tried that technique actually, on the latest build image (focal), and unfortunately it didn't work. I still get 
```
3:07:44 PM: npm ERR! code E401
3:07:44 PM: npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/download/... - authentication token not provided
```

**Comment by robnewton** [comment]
oh wait, I just noticed thats `./netlify` and not `/.netlify`. I think that's why it didnt work. Trying again with a new `netlify` folder in the repo root.

**Comment by robnewton** [comment]
Yep, that was it. It worked! Thanks for the nudge @itsjoekent

**Comment by itsjoekent** [comment]
No problemo! @robnewton

**Pull request closed without merging**
