### PR TITLE
Add Ruby 2.4.1

### PR DESCRIPTION
**Pull request by lcpriest**
I'm aware of https://github.com/netlify/build-image/pull/34, but that PR attempts to drop some backwards compatibility.

### CODE REVIEW

**Comment by lcpriest** [comment]
@rybit anything I need to do to get this merged?

**Comment by rybit** [comment]
nope! I just have to get to it in my inbox :) 

I will be rolling this out when it is done building (probably later today/tomorrow)

**Comment by lcpriest** [comment]
Can you let me know when it's deployed? I tried re-trying my deploy today and no luck yet.

**Comment by lcpriest** [comment]
@rybit Can you let me know when it's deployed? I tried re-trying my deploy today and no luck yet.

**Comment by rybit** [comment]
I am testing it out right now and it should be out in the next few hours. If you write into support they can keep you more up to date.

**Pull request merged**
