### PR TITLE
Remove tmp files

### PR DESCRIPTION
**Pull request by bcomnes**
This clears out tmp files

### CODE REVIEW

**Comment by rybit** [comment]
was this a problem?

**Comment by bcomnes** [comment]
I'm hoping this results in a smaller squashed build image.

**Comment by rybit** [comment]
If you launch the image, do you have files there?

**Comment by bcomnes** [comment]
Yeah, about 450-500mb of files, looks like leftovers from various install processes.

**Comment by rybit** [comment]
nice catch

**Pull request merged**
