### PR TITLE
add expect to handle automate interactive cli

### PR DESCRIPTION
**Pull request by ekoeryanto**

### CODE REVIEW

**Comment by brycekahle** [comment]
Can you describe your use-case?

**Comment by ekoeryanto** [comment]
Hello, 
I have problem in developing vuejs-templates as it installed with interactive mode

see: vuejs/vue-cli#291, renestalder/nuxt-netlify-cms-starter-template#11

**Comment by Harti** [comment]
+1. Using a Dockerfile to set things up.

**Comment by eliranmal** [comment]
@ekoeryanto, i assembled an expect/autoexpect based script for live inspection of vue-cli custom-template files, and called it a dev-server :)

[check it out][1], if you're interested.

---

example-usage




[1]: https://github.com/eliranmal/vue-cli-template-dev-server

**Pull request merged**
