### PR TITLE
Add PHP 7.4

### LINKED ISSUE #365: PHP 7.4
Hello,

PHP 5.6 is EOL and PHP 7.2 is now on security support only.

https://www.php.net/supported-versions.php

I think we need to offer PHP 7.4 ~~(and possibly PHP 7.3)~~

### PR DESCRIPTION
**Pull request by Jamesking56**
Fixes #365

### CODE REVIEW

**Comment by mraerino** [comment]
In order to not bloat the image, let's not include 7.3? does that seem ok?

**Comment by Jamesking56** [comment]
@mraerino So just add 7.4?

**Comment by mraerino** [comment]
yeah, that should be enough

**Comment by Jamesking56** [comment]
@mraerino updated :+1:

**Comment by mraerino** [comment]
Cool. I will see when we can get it rolled to the Netlify CI.

**Comment by Jamesking56** [comment]
Not sure why CI is failing on this

**Comment by Jamesking56** [comment]
@mraerino What are the CI failures on this?

**Comment by Jamesking56** [comment]
@mraerino Any updates on this one? PHP on Netlify won't be getting bugfixes anymore

**Comment by Benaiah** [comment]
@Jamesking56 it looks like the CI failure on this PR was caused by the issue I fixed in #376 - can you rebase this PR onto master now that that's merged?

**Comment by Jamesking56** [comment]
Rebased and passing @Benaiah

**Review by Benaiah — APPROVED** [review]

**Comment by ghost** [comment]
So how do I actually use this?

I'm building a Jigsaw static site.

When I set 7.4 in my netlify.toml file it just threw some error that I can't remember, but basically I'm stuck on PHP 7.2.

**Comment by mraerino** [comment]
@raniesantos since we are not doing tech support in issues, please head over to https://community.netlify.com/ where people will be happy to help.

when doing that, please make sure that
- you're on the latest build image version (xenial currently) - you can set it in the build settings
- to post the contents of your `netlify.toml` and the name of the site where the problem occurs.

**Comment by nelson6e65** [comment]
Hello!

I'm having problem trying to use PHP 7.3:

```
PHP version 7.3 does not exist
```

I'm able to use PHP 7.2. But why not PHP 7.3?

I can't use PHP 7.4 yet.

**Pull request merged**
