### PR TITLE
Update ruby versions with patch updates

### PR DESCRIPTION
**Pull request by brycekahle**

### CODE REVIEW

**Comment by migueldemoura** [comment]
Anything blocking this?

**Comment by rybit** [comment]
It looks fine, but the person that would be doing the change and checking that it is fine is on vacation. We will probably pick this up when he gets back.

**Comment by migueldemoura** [comment]
Thanks @rybit!

**Comment by migueldemoura** [comment]
Any update on this? @rybit

**Comment by DirtyF** [comment]
That is some long vacation 🌴 ☀️ 😎  

Since this was open:

- Ruby 2.5.3 Released
- Ruby 2.4.5 Released
- Ruby 2.3.8 Released

and recently a Snap for Ruby: https://www.ruby-lang.org/en/news/2018/11/08/snap/

Any plan to update Ruby versions before 2.6.0 release in December?

**Comment by rybit** [comment]
Realistically no. :) We are updating our release strategy to be able to handle these issues coming up. 

At the moment you should be able to set `RUBY_VERSION` in your site or toml file to access those other versions.

**Pull request closed without merging**
