### PR TITLE
add python 3.5.2

### PR DESCRIPTION
**Pull request by monty5811**
Add support for python 3.5

### CODE REVIEW

**Comment by dbader** [comment]
Thank you @monty5811 – I'd love to see Python 3.5 support, too. That would make Netlify even more awesome :)

**Comment by fool** [comment]
should notify https://app.intercom.io/a/apps/q245f50x/inbox/_/conversations/6811510396 as well as https://app.intercom.io/a/apps/q245f50x/inbox/_/conversations/6472826390

**Comment by calavera** [comment]
LGTM. I'm going to merge it, but we won't release it until next week.

**Comment by dbader** [comment]
Thank you @calavera!

**Comment by monty5811** [comment]
Thanks @calavera!!

**Pull request merged**
