### PR TITLE
Add Hugo extended (>0.43)

### PR DESCRIPTION
**Pull request by igk1972**
Uncompress necessary files from one deb-package for using a CGO-extension compiled version of Hugo (>0.43).
See https://github.com/netlify/build-image/issues/183 and https://github.com/netlify/build-image/issues/182 

And set expand alias with LD_LIBRARY_PATH - only for hugo extended.

### CODE REVIEW

**Comment by brycekahle** [comment]
@igk1972 We appreciate the PR, but I don't think we are comfortable installing packages designed for Ubuntu 16 on Ubuntu 14. The risk for negative side-effects is too high.

**Comment by igk1972** [comment]
> @igk1972 We appreciate the PR, but I don't think we are comfortable installing packages designed for Ubuntu 16 on Ubuntu 14. The risk for negative side-effects is too high.

But the package is NOT installed on the system. The library is loaded only separately and it is only for hugo-0.43

**Comment by brycekahle** [comment]
> But the package is _not_ installed on the system

I see that now. Let me discuss this with some colleagues.

**Comment by bluestrike2** [comment]
> > But the package is _not_ installed on the system
> 
> I see that now. Let me discuss this with some colleagues.

@brycekahle 

Any movement on the subject, by chance?

**Comment by brycekahle** [comment]
@bluestrike2 I'm in the process of leaving Netlify. Let's get @rybit involved here. He can keep you up to date on discussions.

**Comment by bcomnes** [comment]
Thank you @igk1972 for this, sorry its taken so long, we are considering going with this as a short term solution now.

**Comment by bcomnes** [comment]
After testing this, this will be the interim solution we are using until we can make larger changes to the build-bot.

**Comment by bcomnes** [comment]
An issue with this: Makefile's that reference hugo won't get the alias.  Brainstorming a fix.

**Comment by bcomnes** [comment]
Since this is going to cause more issues for the current situation than without it, I'm going to partially revert some of this.  We'll still keep the shared lib additions, but we won't install extended by default or alias the LD env vars in, since they aren't reliable in different shell contexts.  Also, we are going to expedite making a Ubuntu 16 image available.  Hang tight for more details.

**Pull request merged**
