### PR TITLE
chore: Fix tiny issues in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by danez**
#### Summary

n/t

### CODE REVIEW

**Review by JGAntunes — APPROVED** [review]
📄

**Comment by danez** [comment]
@JGAntunes @kitop Is it expected that circleCI is not triggered when kodiak is merging in the default branch?

**Comment by kitop** [comment]
> @JGAntunes @kitop Is it expected that circleCI is not triggered when kodiak is merging in the default branch?

It is not. Something was off with the webhook, got a 400 response for that. I just re-triggered and now it's building.

**Comment by danez** [comment]
I wonder if it worked now because YOU triggered the webhook and you are properly authorized in circle. But maybe kodiak and other integrations do not have the correct access. Because I have seen the exact same behavior before in this repo in another PR of mine.

**Comment by kitop** [comment]
Oh, interesting! The webhook was sent with the exact same payload, so that's weird. But we've seen it happen with the tags the other day too. I'll try to reach out to CircleCI support to understand what could be going on.

**Pull request merged**
