### PR TITLE
Add pngquant

### PR DESCRIPTION
**Pull request by rycus86**
This PR makes [pngquant](https://pngquant.org/) available in the container, that can potentially produce smaller optimized PNG images than what's available in the image right now.

### CODE REVIEW

**Comment by rycus86** [comment]
Not sure why this has failed on CI, can't see any details. :/
Let me know please if I can do anything to get this passing.

**Comment by bcomnes** [comment]
Erlang failed to install, restarting the build to try again.  We may need to repair that and rebase this.

**Comment by rycus86** [comment]
Thanks for looking into this @bcomnes ! Let me know if you do need me to rebase this.

**Comment by bcomnes** [comment]
Looks like the build is failing.  I'll have to fix that first.  I have a bunch of other things the pipeline, so I'll ping you when we need a rebase.  Thank you for your patients.

**Comment by kitop** [comment]
Closing this PR as the it's against xenial branch and the Xenial image is going to be deprecated: https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

**Pull request closed without merging**
