### PR TITLE
Reduce installed ruby to latest supported versions. 

### PR DESCRIPTION
**Pull request by brycekahle**
Cache custom versions.

Fixes #125 #109

### CODE REVIEW

**Comment by calavera** [comment]
@brycekahle I think we should only install the stable versions listed here:
https://www.ruby-lang.org/en/downloads/

**Comment by brycekahle** [comment]
`2.2.9` is technically not EOL yet. That doesn't happen until 2018-03-31. I cannot install `2.5.0` yet until RVM does another release.

**Comment by calavera** [comment]
> 2.2.9 is technically not EOL yet. That doesn't happen until 2018-03-31. I cannot install 2.5.0 yet until RVM does another release.

ugh, ok, I thought they had a binary already.

**Comment by calavera** [comment]
ship it

**Comment by mitchellcash** [comment]
@brycekahle appreciative of these changes, much more flexible overall and easier to manage from your perspective. When will this make it to Netlify production?

**Comment by brycekahle** [comment]
@mitchellcash I'd say in the next day or two. I'll ping this issue when it is released.

**Comment by brycekahle** [comment]
@mitchellcash The changes are now be live.

**Comment by mitchellcash** [comment]
@brycekahle thanks for the notice!

**Pull request merged**
