### PR TITLE
fix: Install Hugo extended by default

### LINKED ISSUE #182: Support extended Hugo version
Duplicate of: https://github.com/netlify/binrc/issues/16
Opening an issue here as @futuregerald kindly suggested.

**- What is the current behavior?**

From version 0.43 Hugo comes in two flavours, extended version allows native Sass compilation.
Netlify currently does not support extended version:

```
2:28:30 PM: ERROR 2018/07/10 12:28:30 error: failed to transform resource: failed to transform “scss/main.scss” (text/x-scss): this feature is not available in your current Hugo version
```

**Edit: For now, the recommended workflow is to commit your `/resources` folder after building locally with `hugo`.**

**- What is the expected behavior?**

Either download the extended binary by default from now on or allow to specify something like 0.43/extended in netlify.toml.

_extended is added to the release path before the version number:

https://github.com/gohugoio/hugo/releases/download/v0.43/hugo_0.43_Linux-64bit.tar.gz
https://github.com/gohugoio/hugo/releases/download/v0.43/hugo_extended_0.43_Linux-64bit.tar.gz

### PR DESCRIPTION
**Pull request by hrishikesh-k**
#### Summary

Fixes #182 (again)

It appears that the above error has resurfaced. Internal link: https://github.com/netlify/pillar-support/issues/42

---

For us to review and ship your PR efficiently, please perform the following steps:

- [x] Open a [bug/issue](https://github.com/netlify/build-image/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [x] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This ensures your code follows our style guide and passes our tests.
- [x] Update or add tests (if any source code was changed or added) 🧪
- [x] Update the [included software doc](../included_software.md) (if you updated included software) 📄
- [x] Update or add documentation (if features were changed or added) 📝
- [x] Make sure the status checks below are successful ✅

### CODE REVIEW

**Comment by hrishikesh-k** [comment]
Looks like Hugo Extended doesn't have Linux-ARM64 (anymore). Reverted to standard Hugo for ARM 64

**Review by JGAntunes — COMMENTED** [review]
This looks great @Hrishikesh-K! Thank you 🙏

Would you mind adding a test scenario to:
- https://github.com/netlify/build-image/blob/d05976bd3309b73a86eaa327bf80e105ff13f5e4/focal-amd64.yaml#L1-L5

Similar to what we have in:
- https://github.com/netlify/build-image/blob/d05976bd3309b73a86eaa327bf80e105ff13f5e4/focal.yaml#L101-L104

But specifically testing for the presence of the `extended` version?

**Comment by hrishikesh-k** [comment]
Updated the tests!

**Review by JGAntunes — APPROVED** [review]
Thank you @Hrishikesh-K!

**Pull request merged**
