### PR TITLE
feat: update nvm and yarn to latest version

### PR DESCRIPTION
**Pull request by danez**
#### Summary

yarn 1 isn't developed anymore, so it might make sense to use the latest version, because it has the best compatibility with newer versions of yarn.

nvm changelog doesn't seem too interesting, one thing that might be of interest is this line
>nvm_get_download_slug: better architecture selection for M1 Macs

which might help with amd64 build of the image.

### CODE REVIEW

**Comment by JGAntunes** [comment]
Thanks for your contribution @danez 🙏

For yarn specifically, we pin that version at the API level for newly created sites. So we try to have these two version in synch. See here:
- https://github.com/netlify/bitballoon/blob/388344a48b002fd59ab3ba17d8bf4ee274d4c3fc/app/models/repo.rb#L23

**Comment by danez** [comment]
Exactly, wanted to update bitballoon once this is done. But I can prepare a PR

**Comment by danez** [comment]
Here is the bitballoon PR: https://github.com/netlify/bitballoon/pull/13187

**Review by JGAntunes — CHANGES_REQUESTED** [review]
Looks like this test needs updating too (this probably became redundant with the container structure tests so we might consider drop it too I guess 🤔):
- https://github.com/netlify/build-image/blob/146f9d055346de28b685bd81ddf96fd599ee8360/tests/node/yarn.bats#L30-L33

**Comment by JGAntunes** [comment]
> Here is the bitballoon PR: https://github.com/netlify/bitballoon/pull/13187

Thanks! I think once we go through merging and releasing this we can go through releasing the Bitballoon one.

**Comment by danez** [comment]
I fixed it all hopefully.

**Review by JGAntunes — DISMISSED** [review]
🚀

**Comment by danez** [comment]
Only focal is good enough?

**Comment by JGAntunes** [comment]
Yep, that should be enough @danez 👍

**Review by lukasholzer — APPROVED** [review]
LGTM!

**Pull request merged**
