### PR TITLE
Install the gd and sqlite3 PHP extensions to minimally support Drupal

### PR DESCRIPTION
**Pull request by mortenson**
👋 Hi there, I'm the maintainer of [Tome](https://tome.fyi/), an in-development static site generator built with Drupal 8.

This image has almost has everything Drupal needs to run, but is missing the "gd" extension which is required by [Drupal core's composer.json file](https://cgit.drupalcode.org/drupal/tree/core/composer.json#n10), and lacks any database driver.

Tome uses SQLite by default, which is already available as a binary in the image - I would just need the extension to get everything working.

I've verified that my [Netlify site built using Tome](https://github.com/drupal-tome/umami-netlify) works locally using the `./test-tools/test-build.sh` script (thanks for that, by the way!), so I think this is all that's needed to get Drupal minimally working on Netlify.

If you need any other information, please let me know! 🙇

### CODE REVIEW

**Comment by mortenson** [comment]
Wow that was a fast merge! 🐦 Thanks @biilmann

**Comment by pedroborges** [comment]
Is this change already available? I'm developing a plugin to generate static pages for the Kirby CMS and also need support for GD to run the build command on Netlify. Right now I'm getting this error:

```bash
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - claviska/simpleimage 3.3.3 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - claviska/simpleimage 3.3.2 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - claviska/simpleimage 3.3.1 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - claviska/simpleimage 3.3.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - getkirby/cms dev-develop requires claviska/simpleimage 3.3.* -> satisfiable by claviska/simpleimage[3.3.0, 3.3.1, 3.3.2, 3.3.3].
    - Installation request for getkirby/cms dev-develop -> satisfiable by getkirby/cms[dev-develop].
  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.2/cli/php.ini
    - /etc/php/7.2/cli/conf.d/10-opcache.ini
    - /etc/php/7.2/cli/conf.d/10-pdo.ini
    - /etc/php/7.2/cli/conf.d/15-xml.ini
    - /etc/php/7.2/cli/conf.d/20-calendar.ini
    - /etc/php/7.2/cli/conf.d/20-ctype.ini
    - /etc/php/7.2/cli/conf.d/20-dom.ini
    - /etc/php/7.2/cli/conf.d/20-exif.ini
    - /etc/php/7.2/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.2/cli/conf.d/20-ftp.ini
    - /etc/php/7.2/cli/conf.d/20-gettext.ini
    - /etc/php/7.2/cli/conf.d/20-iconv.ini
    - /etc/php/7.2/cli/conf.d/20-json.ini
    - /etc/php/7.2/cli/conf.d/20-mbstring.ini
    - /etc/php/7.2/cli/conf.d/20-phar.ini
    - /etc/php/7.2/cli/conf.d/20-posix.ini
    - /etc/php/7.2/cli/conf.d/20-readline.ini
    - /etc/php/7.2/cli/conf.d/20-shmop.ini
    - /etc/php/7.2/cli/conf.d/20-simplexml.ini
    - /etc/php/7.2/cli/conf.d/20-sockets.ini
    - /etc/php/7.2/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.2/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.2/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.2/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.2/cli/conf.d/20-wddx.ini
    - /etc/php/7.2/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.2/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.2/cli/conf.d/20-xsl.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

Do I need to enable it my `netlify.toml` file?

**Comment by mortenson** [comment]
@pedroborges This has not been deployed yet - I opened https://github.com/netlify/build-image/issues/181 to discuss release timing but the short version is that we have to wait for a new release.

**Comment by pedroborges** [comment]
Thanks for the update, I'm looking forward to it! Since I was gettings errors from a dependency that requires GD, I have hardcoded it for now and committed the vendor folder until this PR goes live.

**Pull request merged**
