### PR TITLE
Pin setuptools to <45 to allow installing pipenv on python 2.7

### PR DESCRIPTION
**Pull request by Benaiah**
Fixes CI failures currently affecting any build-image PRs.

### CODE REVIEW

**Comment by vbrown608** [comment]
I'm not very familiar with the python ecosystem - could you explain what you understood the error to be and why this fixes it?

**Comment by Benaiah** [comment]
https://github.com/pypa/virtualenv/issues/1493 is the underlying issue that this is taking care of. I'm not a Python expert either, but as I understand it `pipenv` depends on `virtualenv`, which in turn requires `setuptools`. `setuptools` recently released a new version `45.0.0` which drops support for Python 2. This causes the build to fail because `pipenv` ends up installing `setuptools>=45`, which raises an error if installed on Python 2. By explicitly installing a version of `setuptools` that supports Python 2, we avoid the build failure that occurs on the next line.

I'm not sure why `pip` is installing a version of `setuptools` that doesn't support the running version of Python.

**Comment by Benaiah** [comment]
https://jenkins.ops.netlify.com/blue/organizations/jenkins/build-image/detail/PR-373/1/pipeline is an example of a CI build that failed because of this issue instead of an issue with the PR itself.

**Review by vbrown608 — APPROVED** [review]
Thanks for explaining, this seems reasonable. My read of the thread is that maybe some mirror for installing Python packages is not respecting the requirement that `virtualenv` should use `setuptools <45.0.0` with Python 2.7, in which case we won't need this forever.

**Comment by vbrown608** [comment]
Thanks for tracking this down!

**Pull request merged**
