### PR TITLE
Upgrade preinstalled Go version to 1.14.4

### PR DESCRIPTION
**Pull request by Benaiah**
Split off from https://github.com/netlify/build-image/pull/406.

### CODE REVIEW

**Comment by erquhart** [comment]
Need a review here when someone has time 🙏 cc/ @mheffner @vbrown608

**Review by mheffner — APPROVED** [review]
:shipit:

**Comment by mheffner** [comment]
actually, looks like there may be a few more minor versions if we want to grab the very latest

**Comment by Benaiah** [comment]
@mheffner good catch; updated the PR to use `1.14.4`.

**Review by mheffner — APPROVED** [review]

**Pull request merged**
